<?php
/**
 * PHP Enums Library
 * Copyright (c) 2011 Tim Kurvers <http://www.moonsphere.net>
 * 
 * This library provides enum functionality similar to the implementation
 * found in Java. It differs from existing libraries by offering one-shot
 * enum constructors through static initialization, enum iteration as well
 * as equality support and value, ordinal and binary lookups.
 * The contents of this file are subject to the MIT License, under which 
 * this library is licensed. See the LICENSE file for the full license.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 * @author  Tim Kurvers <tim@moonsphere.net>
 */
use Websublime\Enum\Enum;

/**
 * This example shows how to work with binary flags generated by the enum library
 */

// When buying a new car, customers may order several additional features  
class CarFeature extends Enum {

    const CONVERTIBLE       = 'Turn your car into a convertible!';
    const CENTRAL_LOCKING   = 'Automatically lock all other doors, with this central locking system';
    const SPOILERS          = 'Fan of the Fast and the Furious? Pimp your car with spoilers';
    const ALARM             = 'Protects your valuables as well as the car itself';
    const SEAT_HEATING      = 'Nice and comfy heated seats for those cold days';

}

/** @end Binary.php**/